# Generated by Django 4.2.25 on 2025-11-03 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reciclagem', '0003_rename_rua_cooperativa_endereco_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='cooperativa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reciclagem.cooperativa', verbose_name='Cooperativa/Ponto de Coleta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='usuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome Completo'),
        ),
    ]
