# Generated by Django 4.2.25 on 2025-11-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_agendamento_cooperativa_agendamento_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('CANCELADO', 'Cancelado pelo Usuário'), ('CONCLUIDO', 'Concluído')], default='AGENDADO', max_length=10),
        ),
    ]
