# Generated by Django 4.2.25 on 2025-11-09 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_cadastro_groups_cadastro_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
