# Generated by Django 4.2.25 on 2025-11-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cadastro', '0003_cadastro_is_staff_alter_cadastro_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission'),
        ),
    ]
