# Generated by Django 4.2.25 on 2025-11-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclagem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperativa',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='pontocoleta',
            name='endereco',
        ),
        migrations.AddField(
            model_name='cooperativa',
            name='numero',
            field=models.CharField(default='S/N', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cooperativa',
            name='rua',
            field=models.CharField(default='Não Informada', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pontocoleta',
            name='horario_funcionamento',
            field=models.CharField(default='S/N', max_length=255, verbose_name='Horário de Funcionamento'),
        ),
        migrations.AddField(
            model_name='pontocoleta',
            name='numero',
            field=models.CharField(default='S/N', max_length=20, verbose_name='Numero'),
        ),
        migrations.AddField(
            model_name='pontocoleta',
            name='rua',
            field=models.CharField(default='Não informado', max_length=100, verbose_name='Rua'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pontocoleta',
            name='tipos_aceitos',
            field=models.TextField(default='Não especificado', verbose_name='Tipos de Materiais Aceitos'),
            preserve_default=False,
        ),
    ]
