# Generated by Django 4.2.25 on 2025-11-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclagem', '0002_remove_cooperativa_endereco_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cooperativa',
            old_name='rua',
            new_name='endereco',
        ),
        migrations.RemoveField(
            model_name='pontocoleta',
            name='rua',
        ),
        migrations.AddField(
            model_name='cooperativa',
            name='horario_funcionamento',
            field=models.CharField(default='S/N', max_length=255, verbose_name='Horário de Funcionamento'),
        ),
        migrations.AddField(
            model_name='cooperativa',
            name='tipos_aceitos',
            field=models.TextField(default='Não especificado', verbose_name='Tipos de Materiais Aceitos'),
        ),
        migrations.AddField(
            model_name='pontocoleta',
            name='endereco',
            field=models.CharField(default='Não informado', max_length=100, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='pontocoleta',
            name='tipos_aceitos',
            field=models.TextField(default='Não especificado', verbose_name='Tipos de Materiais Aceitos'),
        ),
    ]
